import { describe, expect, test } from "vitest";
import { definePolicy, self, unsafeEval, type DefinedPolicy } from "csp-toolkit";
import { generatePolicyString } from "../src/policy/createPolicy";
import { createNewCollection } from "../src/policy/core";
import { cspKeywordForm } from "../src/policy/keywordForm";

/**
 * Serialised policies from csp-toolkit are `directive value; ...` with
 * space‑separated sources. Unserialised edge cases (semicolons in `nonce-` etc.)
 * are not generated by the plugin under test.
 */
function directiveSources(csp: string, name: string): string[] {
  const segments = csp.split(";").map((s) => s.trim());
  const entry = segments.find(
    (s) => s === name || s.startsWith(`${name} `),
  );
  if (!entry || entry === name) return [];
  return entry.slice(name.length + 1).trim().split(/\s+/);
}

describe("generatePolicyString — elem directive inheritance from parent", () => {
  test("inherits external URLs from script-src into script-src-elem when hashes are present", () => {
    const collection = createNewCollection();
    collection["script-src-elem"].set("sha256-dummy", {
      algorithm: "sha256",
      content: "",
    });

    const policy: DefinedPolicy = definePolicy({
      defaultSrc: [self],
      scriptSrcElem: [self],
      scriptSrc: [self, "https://js.stripe.com", "https://js.sentry-cdn.com"],
    });

    const out = generatePolicyString({ collection, policy });
    const src = directiveSources(out, "script-src-elem");
    expect(src).toContain("https://js.stripe.com");
    expect(src).toContain("https://js.sentry-cdn.com");
  });

  test("inherits external URLs from style-src into style-src-elem when hashes are present", () => {
    const collection = createNewCollection();
    collection["style-src-elem"].set("sha256-dummy", {
      algorithm: "sha256",
      content: "",
    });

    const policy: DefinedPolicy = definePolicy({
      defaultSrc: [self],
      styleSrcElem: [self],
      styleSrc: [self, "https://fonts.googleapis.com", "https://example.com"],
    });

    const out = generatePolicyString({ collection, policy });
    const src = directiveSources(out, "style-src-elem");
    expect(src).toContain("https://fonts.googleapis.com");
    expect(src).toContain("https://example.com");
  });

  test("does not copy 'unsafe-eval' from script-src into script-src-elem", () => {
    const collection = createNewCollection();
    collection["script-src-elem"].set("sha256-dummy", {
      algorithm: "sha256",
      content: "",
    });

    const policy: DefinedPolicy = definePolicy({
      defaultSrc: [self],
      scriptSrcElem: [self],
      scriptSrc: [self, unsafeEval, "https://allowed.example.test"],
    });

    const out = generatePolicyString({ collection, policy });
    const src = directiveSources(out, "script-src-elem");
    expect(src).toContain("https://allowed.example.test");
    expect(src).not.toContain(cspKeywordForm(unsafeEval));
  });

  test("does not duplicate a source already on script-src-elem", () => {
    const url = "https://shared.example.test";
    const collection = createNewCollection();
    collection["script-src-elem"].set("sha256-dummy", {
      algorithm: "sha256",
      content: "",
    });

    const policy: DefinedPolicy = definePolicy({
      defaultSrc: [self],
      scriptSrcElem: [self, url],
      scriptSrc: [self, url],
    });

    const out = generatePolicyString({ collection, policy });
    const count = directiveSources(out, "script-src-elem").filter((s) => s === url)
      .length;
    expect(count).toBe(1);
  });

  test("when script-src-elem has no generated hashes, does not pull sources from script-src", () => {
    const collection = createNewCollection();
    expect(collection["script-src-elem"].size).toBe(0);

    const policy: DefinedPolicy = definePolicy({
      defaultSrc: [self],
      scriptSrcElem: [self],
      scriptSrc: [self, "https://not-inherited.example.test"],
    });

    const out = generatePolicyString({ collection, policy });
    const src = directiveSources(out, "script-src-elem");
    expect(src).toEqual([cspKeywordForm(self)]);
    expect(src).not.toContain("https://not-inherited.example.test");
  });
});
